name: groupme-archiver
channels:
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.13=py37_0
  - cffi=1.11.5=py37h342bebf_0
  - chardet=3.0.4=py37_1
  - cryptography=2.3=py37hdbc3d79_0
  - cryptography-vectors=2.3=py37_0
  - idna=2.7=py37_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_0
  - openssl=1.0.2p=h1de35cc_0
  - pip=10.0.1=py37_0
  - pycparser=2.18=py37_1
  - pyopenssl=18.0.0=py37_0
  - pysocks=1.6.8=py37_0
  - python=3.7.0=hc167b69_0
  - readline=7.0=hc1231fa_4
  - requests=2.19.1=py37_0
  - setuptools=40.0.0=py37_0
  - six=1.11.0=py37_1
  - sqlite=3.24.0=ha441bb4_0
  - tabulate=0.8.2=py37_0
  - tk=8.6.7=h35a86e2_3
  - urllib3=1.23=py37_0
  - wheel=0.31.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=hf3cbc9b_2
  - pip:
    - yattag==1.10.0

